/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oscar
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FacturaLbl = new javax.swing.JLabel();
        CompraLbl = new javax.swing.JLabel();
        HoraLbl = new javax.swing.JLabel();
        tarjetaLbl = new javax.swing.JLabel();
        ordenLbl = new javax.swing.JLabel();
        numOrdenLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        efectivoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        FacturaLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FacturaLbl.setText("Su pedido estará listo a las");

        CompraLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CompraLbl.setText("¡Gracias por su compra!");

        HoraLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tarjetaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tarjetaLbl.setText("Por favor, presente su tarjeta de crédito y muestre el siguiente mensaje para pagar");

        ordenLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ordenLbl.setText("Orden:");

        numOrdenLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numOrdenLbl.setText("122");

        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreLbl.setText("Nombre: ");

        fechaLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fechaLbl.setText("Fecha: 17/08/2017");

        efectivoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        efectivoLbl.setText("Por favor, tenga el efectivo listo y muestre el siguiente mensaje para pagar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FacturaLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HoraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ordenLbl)
                                .addGap(18, 18, 18)
                                .addComponent(numOrdenLbl))
                            .addComponent(nombreLbl)
                            .addComponent(fechaLbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(CompraLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tarjetaLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(efectivoLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(CompraLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FacturaLbl)
                    .addComponent(HoraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(tarjetaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(efectivoLbl)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOrdenLbl)
                    .addComponent(ordenLbl))
                .addGap(18, 18, 18)
                .addComponent(nombreLbl)
                .addGap(18, 18, 18)
                .addComponent(fechaLbl)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }
    
    public void mostrarFactura (int tipo, String hora) {
        
        tarjetaLbl.setVisible(false);
        efectivoLbl.setVisible(false);
        HoraLbl.setText(hora);
        
        if (tipo == 0){  
            efectivoLbl.setVisible(true); 
        } else if (tipo == 1){
            tarjetaLbl.setVisible(true);
        }
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompraLbl;
    private javax.swing.JLabel FacturaLbl;
    private javax.swing.JLabel HoraLbl;
    private javax.swing.JLabel efectivoLbl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel numOrdenLbl;
    private javax.swing.JLabel ordenLbl;
    private javax.swing.JLabel tarjetaLbl;
    // End of variables declaration//GEN-END:variables
}
