
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 * Permite al usuario registrarse o ingresar al sistema para poder pedir una orden.
 * @author Rodrigo Zea, Oscar Juárez, Andrés Quan
 * @version 1.0
 */
public class Login extends javax.swing.JFrame {
    //Variables de Instancia
    public static ArrayList<users> usuarios = new ArrayList<>(); 
    Calculos calculos = new Calculos();
    Restaurantes restaurantes = new Restaurantes();
    String usrn, pass;
    boolean unoRegistrado = false;
    boolean cuentaE, nv;
    
    /**
     * Crea una nueva Forma tipo Login
     */
    public Login() {
        initComponents();
        addBtn.setVisible(false);
        rgrLbl.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jUsuarioL = new javax.swing.JLabel();
        UserTF = new javax.swing.JTextField();
        jClaveL = new javax.swing.JLabel();
        vlnBtn = new javax.swing.JButton();
        regrBtn = new javax.swing.JButton();
        clavePF = new javax.swing.JPasswordField();
        loginLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        rgrLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jUsuarioL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jUsuarioL.setText("Usuario:");

        UserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTFActionPerformed(evt);
            }
        });

        jClaveL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jClaveL.setText("Clave:");

        vlnBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        vlnBtn.setText("Validar");
        vlnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlnBtnActionPerformed(evt);
            }
        });

        regrBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        regrBtn.setText("Registrar");
        regrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regrBtnActionPerformed(evt);
            }
        });

        loginLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginLbl.setText("Login");

        addBtn.setText("Añadir");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        rgrLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        rgrLbl.setText("Regresar");
        rgrLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rgrLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rgrLbl)
                    .addComponent(loginLbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jClaveL)
                        .addComponent(jUsuarioL)
                        .addComponent(UserTF)
                        .addComponent(clavePF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(vlnBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regrBtn)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rgrLbl)
                .addGap(18, 18, 18)
                .addComponent(loginLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsuarioL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jClaveL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clavePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vlnBtn)
                    .addComponent(regrBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //La acción que realiza el botón de "Validar"
    private void vlnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlnBtnActionPerformed
        // Cuando se le da clic al botón validar que haga esto
        // Se consigue los datos ingresados por el usuario en los textbox de user y password
       
        calculos.usuariosCalc = usuarios;
        restaurantes.usuariosRest = usuarios;
        
       usrn = UserTF.getText();
       pass = clavePF.getText();
              
       calculos.Validar(usrn, pass);
           
    }//GEN-LAST:event_vlnBtnActionPerformed

    //La acción que realiza el botón de "Registrar"
    private void regrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regrBtnActionPerformed
        //Solo cambia de pantalla a la de registrar
        
        loginLbl.setText("Registrar");
        borrarTxt();
        vlnBtn.setVisible(false);
        regrBtn.setVisible(false);
        addBtn.setVisible(true);
        rgrLbl.setVisible(true);
    }//GEN-LAST:event_regrBtnActionPerformed

    //No se usó (NSU)
    private void UserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTFActionPerformed

    //La acción que realiza el botón de Agregar
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //Se consigue lo que hay escrito en los textbox de User y Pass
        //Boolean de que existe se pone como falso porque aún no se crea la cuenta
        usrn = UserTF.getText();
        pass = clavePF.getText();
        
        calculos.usuariosCalc = usuarios;
       
        calculos.agregarUsuario(usrn, pass);


    }//GEN-LAST:event_addBtnActionPerformed

    //Acción que realiza el botón de registrar
    private void rgrLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgrLblMouseClicked
        //Si el usuario quiere regresar a la pantalla de Login cambiar el texto y se muestren los botones
        loginLbl.setText("Login");
        borrarTxt();
        vlnBtn.setVisible(true);
        regrBtn.setVisible(true);
        addBtn.setVisible(false);
        rgrLbl.setVisible(false);
    }//GEN-LAST:event_rgrLblMouseClicked

    /**
     * Se encarga de borrar el texto en los textfields respectivos.
     */
    public void borrarTxt(){
        UserTF.setText("");
        clavePF.setText("");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserTF;
    private javax.swing.JButton addBtn;
    private javax.swing.JPasswordField clavePF;
    private javax.swing.JLabel jClaveL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jUsuarioL;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JButton regrBtn;
    private javax.swing.JLabel rgrLbl;
    private javax.swing.JButton vlnBtn;
    // End of variables declaration//GEN-END:variables
}
