
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rodrigo Zea, Oscar Juárez, Andrés Quan
 * @version 1.0
 */

//Variables de instancia
public class Menu extends javax.swing.JFrame {
public static ArrayList<users> usuariosMenu = new ArrayList<>();
Calculos calculos = new Calculos();
int precioC, precioB, precioCh, pTotal = 0;
int HoraAb, HoraCe, decision;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

    }
    //Constructor con parámetros, dependiendo la hora de apertura, cierre y la opción de restaurante que usó
    public Menu(int x, int horaAb, int horaCe) {
        initComponents();
        decision = x;
        pasarHora(horaAb, horaCe);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuLbl = new javax.swing.JLabel();
        ordLbl = new javax.swing.JLabel();
        menuLbl1 = new javax.swing.JLabel();
        menuLbl2 = new javax.swing.JLabel();
        menuLbl3 = new javax.swing.JLabel();
        comidaCbx = new javax.swing.JComboBox<>();
        bebidaCbx = new javax.swing.JComboBox<>();
        chipsCbx = new javax.swing.JComboBox<>();
        continueBtn = new javax.swing.JButton();
        ordLbl1 = new javax.swing.JLabel();
        ordLbl2 = new javax.swing.JLabel();
        ordLbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        menuLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLbl.setText("Menú");

        ordLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordLbl.setText("Seleccione su orden:");

        menuLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLbl1.setText("Comida: ");

        menuLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLbl2.setText("Chips:");

        menuLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLbl3.setText("Bebida:");

        comidaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comidaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidaCbxActionPerformed(evt);
            }
        });

        bebidaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bebidaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidaCbxActionPerformed(evt);
            }
        });

        chipsCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chipsCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipsCbxActionPerformed(evt);
            }
        });

        continueBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        continueBtn.setText("Continuar");
        continueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueBtnMouseClicked(evt);
            }
        });
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        ordLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordLbl1.setText("Total:");

        ordLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordLbl2.setText("Q");

        ordLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordLbl3.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuLbl1)
                            .addComponent(ordLbl)
                            .addComponent(menuLbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comidaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menuLbl3)
                                    .addComponent(bebidaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ordLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ordLbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ordLbl3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuLbl2)
                            .addComponent(chipsCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(menuLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ordLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuLbl1)
                    .addComponent(menuLbl2)
                    .addComponent(menuLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comidaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bebidaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chipsCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordLbl1)
                    .addComponent(ordLbl2)
                    .addComponent(ordLbl3))
                .addGap(11, 11, 11)
                .addComponent(continueBtn)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Si le da al botón de continuar
    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        //Si el precio es mayor a 0, que el usuario pueda proceder a la próxima pantalla
        if (pTotal > 0){
           Orden order = new Orden(pTotal, HoraAb, HoraCe);
           order.setVisible(true);
           this.setVisible(false);
        } else {
        //Se muestra un error, que debe seleccionar opciones    
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un mínimo de 2 opciones", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_continueBtnActionPerformed
    
    
    private void comidaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidaCbxActionPerformed
        //Si cambia el valor del combobox entonces que se consigan los precios
      precioC = calculos.setPreciosC(comidaCbx);
      pTotal = calculos.sumar(ordLbl3,precioC,precioB,precioCh);
      ordLbl3.setText(pTotal+"");
    }//GEN-LAST:event_comidaCbxActionPerformed

    private void bebidaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidaCbxActionPerformed
        //Si cambia el valor del combobox de bebida entonces que se consigan los precios
       precioB = calculos.setPreciosB(bebidaCbx);
       pTotal = calculos.sumar(ordLbl3,precioC,precioB,precioCh);
       ordLbl3.setText(pTotal+"");
    }//GEN-LAST:event_bebidaCbxActionPerformed

    private void chipsCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipsCbxActionPerformed
        //Si cambia el valor del combobox de chips entonces que se consigan los precios
        precioCh = calculos.setPreciosCh(chipsCbx);
        pTotal = calculos.sumar(ordLbl3,precioC,precioB,precioCh);
        ordLbl3.setText(pTotal+"");
    }//GEN-LAST:event_chipsCbxActionPerformed

    //NSU
    private void continueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtnMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_continueBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        calculos.showOpts(decision, comidaCbx, bebidaCbx, chipsCbx);
        
    }//GEN-LAST:event_formWindowOpened

    public void pasarHora(int horaAb, int horaCe){
        //Se envía la hora de apertura y cierre al próximo form
        HoraAb = horaAb;
        HoraCe = horaCe;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bebidaCbx;
    private javax.swing.JComboBox<String> chipsCbx;
    private javax.swing.JComboBox<String> comidaCbx;
    private javax.swing.JButton continueBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuLbl;
    private javax.swing.JLabel menuLbl1;
    private javax.swing.JLabel menuLbl2;
    private javax.swing.JLabel menuLbl3;
    private javax.swing.JLabel ordLbl;
    private javax.swing.JLabel ordLbl1;
    private javax.swing.JLabel ordLbl2;
    private javax.swing.JLabel ordLbl3;
    // End of variables declaration//GEN-END:variables
}
