
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rodrigo Zea, Oscar Juárez, Andrés Quan
 * @version 1.0
 */
public class Restaurantes extends javax.swing.JFrame {
    String descripcion, horario, nombre;
    /**
     * Creates new form Restaurantes
     */
    public Restaurantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
<<<<<<< HEAD
        RestaurantesLbl = new javax.swing.JLabel();
        bBrosLbl = new javax.swing.JLabel();
        GitanneLbl = new javax.swing.JLabel();
        REDLbl = new javax.swing.JLabel();
        MonchisLbl = new javax.swing.JLabel();
        PicnicLbl = new javax.swing.JLabel();
        gGreenLbl = new javax.swing.JLabel();
=======
        restLbl = new javax.swing.JLabel();
        ggLbl = new javax.swing.JLabel();
        cgLbl = new javax.swing.JLabel();
        bbLbl = new javax.swing.JLabel();
        pnLbl = new javax.swing.JLabel();
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

<<<<<<< HEAD
        RestaurantesLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        RestaurantesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RestaurantesLbl.setText("Restaurantes");
        RestaurantesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantesLblMouseClicked(evt);
            }
        });

        bBrosLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bBrosLbl.setText("Bagel Bros");

        GitanneLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GitanneLbl.setText("Gitanne");

        REDLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        REDLbl.setText("RED");

        MonchisLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MonchisLbl.setText("Monchis");

        PicnicLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PicnicLbl.setText("Picnic");

        gGreenLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gGreenLbl.setText("Go Green");
=======
        restLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        restLbl.setText("Seleccione su restaurante:");

        ggLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ggLbl.setText("Go Green");
        ggLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ggLblMouseClicked(evt);
            }
        });

        cgLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cgLbl.setText("Cafe Gitane");
        cgLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cgLblMouseClicked(evt);
            }
        });

        bbLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bbLbl.setText("Bagel Bros");
        bbLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbLblMouseClicked(evt);
            }
        });

        pnLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLbl.setText("Picnic");
        pnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLblMouseClicked(evt);
            }
        });
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RestaurantesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gGreenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(REDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PicnicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GitanneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBrosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonchisLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addContainerGap())
=======
                .addGap(206, 206, 206)
                .addComponent(restLbl)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ggLbl)
                    .addComponent(cgLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnLbl)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(407, Short.MAX_VALUE)
                    .addComponent(bbLbl)
                    .addGap(101, 101, 101)))
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                .addComponent(RestaurantesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bBrosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gGreenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(REDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GitanneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PicnicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonchisLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
=======
                .addGap(34, 34, 34)
                .addComponent(restLbl)
                .addGap(99, 99, 99)
                .addComponent(ggLbl)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnLbl)
                    .addComponent(cgLbl))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(bbLbl)
                    .addContainerGap(263, Short.MAX_VALUE)))
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void RestaurantesLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantesLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantesLblMouseClicked

=======
    private void ggLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ggLblMouseClicked
        // TODO add your handling code here:
        showDetails(1);
    }//GEN-LAST:event_ggLblMouseClicked

    private void bbLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbLblMouseClicked
        // TODO add your handling code here:
        showDetails(2);
    }//GEN-LAST:event_bbLblMouseClicked

    private void cgLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgLblMouseClicked
        // TODO add your handling code here:
        showDetails(3);
    }//GEN-LAST:event_cgLblMouseClicked

    private void pnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLblMouseClicked
        // TODO add your handling code here:
        showDetails(4);
    }//GEN-LAST:event_pnLblMouseClicked

    public void showDetails(int x){ 
        int opt = x;
        switch(opt){
            case 1:  
              nombre = ggLbl.getText();  
              descripcion = "Provee una variedad de alimentos más saludables que los de otros restaurantes";
              horario = "10 AM - 3:30 PM";
              break;
            case 2:
              nombre = bbLbl.getText();    
              descripcion = "Ofrece sandwiches de tipo Bagel, los cuales pueden ser una alternativa a sandwiches normales";
              horario = "8:30 AM - 2:00 PM";
              break;
            case 3:
              nombre = cgLbl.getText();    
              descripcion = "Ofrece meriendas simples para un receso o una variedad de almuerzos";
              horario = "6:30 AM - 5:00 PM";
              break;
            case 4:
              nombre = pnLbl.getText();    
              descripcion = "Ofrece opciones de comida más caseras y tradicionales que otros restaurantes";  
              horario = "7 AM - 3:00 PM";
              break;
        }
        
        JOptionPane.showConfirmDialog(null, descripcion + "\n" + "Horario: " + horario, nombre, JOptionPane.YES_NO_OPTION);
       
    }
    
    
    
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel GitanneLbl;
    private javax.swing.JLabel MonchisLbl;
    private javax.swing.JLabel PicnicLbl;
    private javax.swing.JLabel REDLbl;
    private javax.swing.JLabel RestaurantesLbl;
    private javax.swing.JLabel bBrosLbl;
    private javax.swing.JLabel gGreenLbl;
    private javax.swing.JPanel jPanel1;
=======
    private javax.swing.JLabel bbLbl;
    private javax.swing.JLabel cgLbl;
    private javax.swing.JLabel ggLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pnLbl;
    private javax.swing.JLabel restLbl;
>>>>>>> 9d7215a6f5c47777521a250d834a80823744011b
    // End of variables declaration//GEN-END:variables
}
