
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Permite al usuario seleccionar el restaurante que desee
 * @author Rodrigo Zea, Oscar Juárez, Andrés Quan
 * @version 1.0
 */
public class Restaurantes extends javax.swing.JFrame {
    //Variables de instancia
    Calculos calculos = new Calculos();
    Menu menu = new Menu();
    public static ArrayList<users> usuariosRest = new ArrayList<>();
   /*String descripcion, horario, nombre;
    int horaAb, horaCe;*/
    /**
     * Creates new form Restaurantes
     */
    public Restaurantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        restLbl = new javax.swing.JLabel();
        ggLbl = new javax.swing.JLabel();
        cgLbl = new javax.swing.JLabel();
        bbLbl = new javax.swing.JLabel();
        pnLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        restLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        restLbl.setText("Seleccione su restaurante:");

        ggLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ggLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gGreen.png"))); // NOI18N
        ggLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ggLblMouseClicked(evt);
            }
        });

        cgLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cGitane.png"))); // NOI18N
        cgLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cgLblMouseClicked(evt);
            }
        });

        bbLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bbLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bBros.png"))); // NOI18N
        bbLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbLblMouseClicked(evt);
            }
        });

        pnLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picnic.png"))); // NOI18N
        pnLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ggLbl)
                        .addGap(107, 107, 107)
                        .addComponent(bbLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cgLbl)
                        .addGap(88, 88, 88)
                        .addComponent(pnLbl)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(restLbl)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(restLbl)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ggLbl)
                    .addComponent(bbLbl))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cgLbl)
                    .addComponent(pnLbl))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ggLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ggLblMouseClicked
        //Si se hace clic a GoGreen que se pongan los detalles del método showDetails
        calculos.showDetails(1);   
        this.setVisible(false);
    }//GEN-LAST:event_ggLblMouseClicked

    private void bbLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbLblMouseClicked
        //Si se hace clic a Bagel Bros que se pongan los detalles del método showDetails
        calculos.showDetails(2);
        this.setVisible(false);
    }//GEN-LAST:event_bbLblMouseClicked

    private void cgLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgLblMouseClicked
        //Si se hace clic a Cafe Gitane que se pongan los detalles del método showDetails
        calculos.showDetails(3);
        this.setVisible(false);
    }//GEN-LAST:event_cgLblMouseClicked

    private void pnLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLblMouseClicked
        //Si se hace clic a Picnic que se pongan los detalles del método showDetails
        calculos.showDetails(4);
        this.setVisible(false);
    }//GEN-LAST:event_pnLblMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        menu.usuariosMenu = usuariosRest;
    }//GEN-LAST:event_formWindowOpened
    
    //Que se muestren los detalles dependiendo del restaurante que se eligió
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bbLbl;
    private javax.swing.JLabel cgLbl;
    private javax.swing.JLabel ggLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pnLbl;
    private javax.swing.JLabel restLbl;
    // End of variables declaration//GEN-END:variables
}
